feat: Initial version of warden-exporter
warden-protocol/warden-exporter pull request #1
Opened 2024-04-23 15:20 UTC by jlehtimaki

Creates the initial version of Prometheus exporter that exports the following metrics:
- Spaces
- Keys
    - ECDSA
    - EDDSA
    - Pending
- Keychains
- Accounts
- Actions

2024-04-24 11:34 UTC, Pitasi requested changes
some nitpicking but looks good to me 😁

2024-04-24 11:44 UTC, jlehtimaki commented on pkg/grpc/grpc.go
> +		req := warden.QueryAllKeysRequest{Pagination: &query.PageRequest{Key: key}, DeriveAddresses: addressTypes}
Does this default to all Addresstypes or why is this removed?

2024-04-24 11:47 UTC, Pitasi commented on pkg/grpc/grpc.go
> +		req := warden.QueryAllKeysRequest{Pagination: &query.PageRequest{Key: key}, DeriveAddresses: addressTypes}
no, so basically you don't need to derive any address if you only care about the key 

that field is for deriving the public key into Ethereum, Osmos , etc. addresses, but in this case it's not needed

2024-04-25 07:26 UTC, Pitasi approved these changes

2024-04-25 07:27 UTC, merged